[global]

[logger]
level = "info"
messageFormat = "%(asctime)s	%(levelname)s	%(name)s	%(message)s"

[client]
showErrorDetails = true

[runner]

[server]
port = 8501
maxUploadSize = 1
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[mapbox]

[theme]

[secrets]
